services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=testdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flask_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: your_database_name
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
